name: Docker CI/CD

on:
  workflow_run:
    workflows:
      - Lint         # Flujo del que depende
    types:
      - completed
  push:
    branches: [ main ]
    paths:
      - inventario/app/**
  pull_request:
    branches: [ main ]
    paths:
      - inventario/app/**

jobs:
  build:
    name: build and push Docker image
    runs-on: ubuntu-latest
    steps: 
      # 1 
      - uses: actions/checkout@v4
      # 2  
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DHUB_USER }}
          password: ${{ secrets.DHUB_TOKEN }}
      # 3   
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: inventario/
          push: true 
          tags: ${{ secrets.DHUB_USER }}/api-andrada:latest

  # código añadido
  aws:
    name: Deploy image to aws
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # 1
    - name: copy docker compose via ssh key  
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USER }}
        port: 22 # ${{ secrets.PORT }}
        key: ${{ secrets.EC2_KEY }}
        source: inventario/compose.yml
        target: /home/admin
    # 2
    - name: script deploy docker services 
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22  # ${{ secrets.PORT }}
        script: |
            sleep 30
            cd inventario
            docker compose down --rmi all
            docker compose up -d